(define (add1 x)
  (+ x 1))
(define (add2 x)
  (+ x 2))
(define (add3 x)
  (+ x 3))
(define (add4 x)
  (+ x 4))
(define (add5 x)
  (+ x 5))
(define (add6 x)
  (+ x 6))
(define (add7 x)
  (+ x 7))
(define (add8 x)
  (+ x 8))
(define (add9 x)
  (+ x 9))

(add1 (add2 (add3 (add4 (add5 (add6 (add7 (add8 (add9 -3)))))))))

